Solved Form Validation Issue #29
siv2r/kidney-exchange pull request #62
Opened 2021-03-11 11:58 UTC by Spurthi7768

For address line 1 I have removed supernumeric method and for city I have created new method called lettersandspace. Please go through the code and let me know if there are any changes.

2021-03-11 13:43 UTC, siv2r commented on js/editPairForm.js
> +          lettersandspace:true
Instead of creating a new function(i.e, `lettersandspace`). Can you reuse the `supernumeric` method here?

2021-03-12 14:06 UTC, Spurthi7768 commented
I have tried to reuse the supernumeric method. Can you check the code once again?

2021-03-12 14:31 UTC, siv2r requested changes

2021-03-12 14:31 UTC, siv2r commented on js/editPairForm.js
> +      return this.optional(element) || /^[A-Za-z0-9_,-.' /s ]+$/.test(value);
no need to add a `/s` here since ` ` (space is included after `'`) is present in the regex.

2021-03-12 14:31 UTC, siv2r commented on js/editPairForm.js
> +      return this.optional(element) || /^[A-Za-z0-9_,-.' /s ]+$/.test(value);
Remain all looks fine!! Just make this change and I will merge it :)

2021-03-12 14:45 UTC, Spurthi7768 commented
@siv2r I have removed the space character. Sorry for the trouble caused!

2021-03-12 14:49 UTC, siv2r commented
@Spurthi7768 There was no trouble caused!! This is the process :)

2021-03-12 14:49 UTC, merged